---

- name: Cisco APIC controller configuration and queries
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: test
      debug: 
        var: hostvars

    - name: include role aci 
      include_role:
        name: network-aci
    
    - name: include role aci 
      include_role:
        name: network-acis