---

- name: Cisco APIC controller configuration and queries
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: include aci role
      include_tasks:
        name: ../roles/network_aci/tasks/main.yml
